//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileAppServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMEXUser
    {
        public long Id { get; set; }
        public string FullName { get; set; }
        public Nullable<long> CBOSID { get; set; }
        public string TaxNo { get; set; }
        public string RegistrationNumber { get; set; }
        public string MobileNo { get; set; }
        public string LoginName { get; set; }
        public string Password { get; set; }
        public string UserType { get; set; }
        public string Email { get; set; }
        public string Orgnization { get; set; }
        public string Branch { get; set; }
        public Nullable<int> OrgCode { get; set; }
        public Nullable<int> BranchCode { get; set; }
        public Nullable<int> Role { get; set; }
        public Nullable<int> GroupCode { get; set; }
        public bool IsFirstLogin { get; set; }
        public bool IsMobileVerified { get; set; }
        public bool IsExpired { get; set; }
        public bool IsActive { get; set; }
    }
}
