//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileAppServices.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MIMEXEntities : DbContext
    {
        public MIMEXEntities()
            : base("name=MIMEXEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<HelpAnswers> HelpAnswers { get; set; }
        public virtual DbSet<IMEXUser> IMEXUser { get; set; }
        public virtual DbSet<vClaim> vClaim { get; set; }
        public virtual DbSet<vClaimForBank> vClaimForBank { get; set; }
        public virtual DbSet<vClaimForTrader> vClaimForTrader { get; set; }
        public virtual DbSet<vClaimSettlement> vClaimSettlement { get; set; }
        public virtual DbSet<vClientInquery> vClientInquery { get; set; }
        public virtual DbSet<vContract> vContract { get; set; }
        public virtual DbSet<vContractCommodity> vContractCommodity { get; set; }
        public virtual DbSet<vContractPaymentMethod> vContractPaymentMethod { get; set; }
        public virtual DbSet<vContractRequest> vContractRequest { get; set; }
        public virtual DbSet<vContractRequestCommodity> vContractRequestCommodity { get; set; }
        public virtual DbSet<vContractRequestPaymentMethod> vContractRequestPaymentMethod { get; set; }
        public virtual DbSet<vExCommodity> vExCommodity { get; set; }
        public virtual DbSet<vExForm> vExForm { get; set; }
        public virtual DbSet<vExFormCommodity> vExFormCommodity { get; set; }
        public virtual DbSet<vIMEXUser> vIMEXUser { get; set; }
        public virtual DbSet<vImForm> vImForm { get; set; }
        public virtual DbSet<vImFormCommodity> vImFormCommodity { get; set; }
        public virtual DbSet<vIssue> vIssue { get; set; }
        public virtual DbSet<vLicense> vLicense { get; set; }
        public virtual DbSet<vLicenseCommodity> vLicenseCommodity { get; set; }
        public virtual DbSet<vLicenseRequest> vLicenseRequest { get; set; }
        public virtual DbSet<vLicenseRequestCommodity> vLicenseRequestCommodity { get; set; }
        public virtual DbSet<vOperation> vOperation { get; set; }
        public virtual DbSet<vOperationPaymentMethod> vOperationPaymentMethod { get; set; }
        public virtual DbSet<vOperationRequest> vOperationRequest { get; set; }
        public virtual DbSet<vOperationRequestCommodity> vOperationRequestCommodity { get; set; }
        public virtual DbSet<vOperationRequestPaymentMethod> vOperationRequestPaymentMethod { get; set; }
        public virtual DbSet<vPayment> vPayment { get; set; }
        public virtual DbSet<vRelatedObject> vRelatedObject { get; set; }
        public virtual DbSet<vSupportedDouments> vSupportedDouments { get; set; }
        public virtual DbSet<database_firewall_rules> database_firewall_rules { get; set; }
        public virtual DbSet<vOperationCommodity> vOperationCommodity { get; set; }
        public virtual DbSet<vOperationTransfer> vOperationTransfer { get; set; }
        public virtual DbSet<vMaturity> vMaturity { get; set; }
        public virtual DbSet<vMaturityForTrader> vMaturityForTrader { get; set; }
        public virtual DbSet<vMaturitySettlement> vMaturitySettlement { get; set; }
        public virtual DbSet<vMaturityStatus> vMaturityStatus { get; set; }
    }
}
