//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileAppServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vClaim
    {
        public long ClaimCode { get; set; }
        public long FormCode { get; set; }
        public decimal Amount { get; set; }
        public string PaymentMethodNameAR { get; set; }
        public string CurrencyShortName { get; set; }
        public string CommodityNameAR { get; set; }
        public long TaxNumber { get; set; }
        public long CBOSID { get; set; }
        public decimal PaymentPercent { get; set; }
        public long ContractCode { get; set; }
        public System.DateTime DueDate { get; set; }
        public decimal Quantity { get; set; }
        public decimal ClaimDeduction { get; set; }
        public Nullable<decimal> ClaimRemaining { get; set; }
        public long PaymentMethodCode { get; set; }
        public decimal AmountUSD { get; set; }
        public string DueDateString { get; set; }
        public bool IsContract { get; set; }
        public long Bank { get; set; }
        public long BankBranch { get; set; }
        public long ClaimId { get; set; }
        public System.Guid UGUID { get; set; }
        public System.DateTime CreationDate { get; set; }
        public long Measurement { get; set; }
        public string FullNameEnglish { get; set; }
        public string BankNameAR { get; set; }
        public string BranchNameAR { get; set; }
        public string Password { get; set; }
        public string LoginName { get; set; }
        public string FullName { get; set; }
    }
}
