//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileAppServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vClaimSettlement
    {
        public long ClaimSettlementId { get; set; }
        public long ClaimSettlementCode { get; set; }
        public long ClaimCode { get; set; }
        public long PaymentCode { get; set; }
        public System.DateTime CreationDate { get; set; }
        public decimal Deduction { get; set; }
        public long Status { get; set; }
        public long FlowStatus { get; set; }
        public long DataEntereer { get; set; }
        public long FirstApproval { get; set; }
        public long SecondApproval { get; set; }
        public string RejectionNotes { get; set; }
        public long IsDeleted { get; set; }
        public Nullable<decimal> DeductionUSD { get; set; }
        public string FlowStatusNameEX { get; set; }
        public long Bank { get; set; }
        public long BankBranch { get; set; }
        public long FormCode { get; set; }
        public string LoginName { get; set; }
        public string Password { get; set; }
        public string CurrencyShortName { get; set; }
        public string FullName { get; set; }
    }
}
