//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileAppServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vClientInquery
    {
        public Nullable<decimal> RequiredClaims { get; set; }
        public long CBOSID { get; set; }
        public string FullNameArabic { get; set; }
        public string ClientStatusNameAR { get; set; }
        public long Status { get; set; }
        public string LoginName { get; set; }
        public string Password { get; set; }
        public decimal RequiredMaturity { get; set; }
        public decimal DefaultedTransfers { get; set; }
    }
}
