//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileAppServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vContractRequest
    {
        public Nullable<long> ContractRequestCode { get; set; }
        public System.DateTime CreationTime { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public string ImporterName { get; set; }
        public string ImporterAddress { get; set; }
        public string CountryNameAR { get; set; }
        public decimal TotalValue { get; set; }
        public string CurrencyShortName { get; set; }
        public string BankNameAR { get; set; }
        public string BranchNameAR { get; set; }
        public Nullable<long> TaxNo { get; set; }
        public string RegistrationNumber { get; set; }
        public string ShipingTypeNameAR { get; set; }
        public string FlowStatusNameContract { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
        public string LoginName { get; set; }
        public string CBOSID { get; set; }
        public string Custom_Unit_Name_AR { get; set; }
        public string Password { get; set; }
        public long Bank { get; set; }
        public long BankBranch { get; set; }
        public long ShipingTypeCode { get; set; }
        public int Custom_UnitPK { get; set; }
        public long CountryCode { get; set; }
        public long CurrencyCode { get; set; }
        public string ArrivalPort { get; set; }
        public int IsTraderEditable { get; set; }
        public string FullName { get; set; }
    }
}
