//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileAppServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vContract
    {
        public long ContractCode { get; set; }
        public System.DateTime CreationTime { get; set; }
        public string CreationDateString { get; set; }
        public System.DateTime ExpirationDate { get; set; }
        public string ExpirationDateString { get; set; }
        public long TaxNo { get; set; }
        public string FullNameArabic { get; set; }
        public string FullNameEnglish { get; set; }
        public string ImporterName { get; set; }
        public string ImporterAddress { get; set; }
        public string BankNameAR { get; set; }
        public string BranchNameAR { get; set; }
        public string LoadingPortNameAr { get; set; }
        public string ArrivalPort { get; set; }
        public string CountryNameAR { get; set; }
        public string ShipingTypeNameAR { get; set; }
        public string FlowStatusNameContract { get; set; }
        public decimal TotalValue { get; set; }
        public string CurrencyShortName { get; set; }
        public string RegistrationNumber { get; set; }
        public string Notes { get; set; }
        public string RejectionNotes { get; set; }
        public string UGUID { get; set; }
        public string DataEntereer { get; set; }
        public string FirstApproval { get; set; }
        public long Bank { get; set; }
        public long BankBranch { get; set; }
        public string SecondApproval { get; set; }
        public string LoadingPortShortName { get; set; }
        public string LoginName { get; set; }
        public string Password { get; set; }
    }
}
