//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileAppServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vContractCommodity
    {
        public long ContractCommoidityId { get; set; }
        public Nullable<long> ContractCommoidityCode { get; set; }
        public long Contract { get; set; }
        public long Commodity { get; set; }
        public decimal Quantity { get; set; }
        public long Measurement { get; set; }
        public decimal UnitPrice { get; set; }
        public string CommodityNameAR { get; set; }
        public string MeasurementUnitNameEN { get; set; }
        public string LoginName { get; set; }
        public string Password { get; set; }
        public long Bank { get; set; }
        public long BankBranch { get; set; }
        public string CommodityCusCode { get; set; }
    }
}
