//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileAppServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vExForm
    {
        public long FormId { get; set; }
        public long FormCode { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string CreationDateString { get; set; }
        public string BankSerial { get; set; }
        public long Contract { get; set; }
        public long CBOSID { get; set; }
        public decimal TotalValue { get; set; }
        public decimal TotalValueUSD { get; set; }
        public string Note { get; set; }
        public long Status { get; set; }
        public long FlowStatus { get; set; }
        public long DataEntereer { get; set; }
        public long FirstApproval { get; set; }
        public long SecondApproval { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsContract { get; set; }
        public string RejectionNotes { get; set; }
        public bool Returnable { get; set; }
        public long Bank { get; set; }
        public long BankBranch { get; set; }
        public string UGUID { get; set; }
        public string DataEntereerName { get; set; }
        public string FirstApprovalName { get; set; }
        public string SecondApprovalName { get; set; }
        public int CustomLoadStatus { get; set; }
        public System.DateTime CreationTime { get; set; }
        public System.DateTime ExpirationDate { get; set; }
        public long ValidityPeriod { get; set; }
        public long LoadingPort { get; set; }
        public string ImporterName { get; set; }
        public string ImporterAddress { get; set; }
        public long Destination { get; set; }
        public string ArrivalPort { get; set; }
        public decimal ContractTotal { get; set; }
        public long ShipingType { get; set; }
        public long ContractStatus { get; set; }
        public string Notes { get; set; }
        public string Expr1 { get; set; }
        public string RegistrationNumber { get; set; }
        public string BankNameAR { get; set; }
        public string ShipingTypeNameAR { get; set; }
        public string BranchNameAR { get; set; }
        public string FlowStatusNameEX { get; set; }
        public string CountryNameAR { get; set; }
        public string LoginName { get; set; }
        public string Password { get; set; }
        public string Custom_Unit_Name_AR { get; set; }
        public string FullNameAR { get; set; }
        public string CurrencyShortName { get; set; }
        public string FullName { get; set; }
    }
}
