//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileAppServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vExFormCommodity
    {
        public string CommodityNameAR { get; set; }
        public decimal UnitPrice { get; set; }
        public long FormCode { get; set; }
        public decimal Quantity { get; set; }
        public string MeasurementUnitNameAR { get; set; }
        public long CommodityCode { get; set; }
        public string MeasurementUnitNameEN { get; set; }
        public string LoginName { get; set; }
        public string Password { get; set; }
        public long Bank { get; set; }
        public long BankBranch { get; set; }
    }
}
