//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileAppServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vImForm
    {
        public long FormCode { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string CreationDateString { get; set; }
        public long Bank { get; set; }
        public long BankBranch { get; set; }
        public long Operation { get; set; }
        public decimal TotalValue { get; set; }
        public long Currency { get; set; }
        public decimal TotalValueUSD { get; set; }
        public string LoadingPort { get; set; }
        public long CarrierType { get; set; }
        public string Carrier { get; set; }
        public Nullable<long> ArrivalPort { get; set; }
        public string Note { get; set; }
        public long Status { get; set; }
        public long FlowStatus { get; set; }
        public long DataEntereer { get; set; }
        public long FirstApproval { get; set; }
        public long SecondApproval { get; set; }
        public string RejectionNotes { get; set; }
        public bool IsDeleted { get; set; }
        public string BillOfLading { get; set; }
        public string CurrencyShortName { get; set; }
        public string BankNameAR { get; set; }
        public string BranchNameAR { get; set; }
        public string FullName { get; set; }
        public string LoadingPortNameAr { get; set; }
        public string FlowStatusNameIM { get; set; }
        public string CarrierTypeNameAr { get; set; }
        public Nullable<long> CBOSID { get; set; }
        public Nullable<long> TaxNumber { get; set; }
        public long FormId { get; set; }
        public long OperationCode { get; set; }
        public string ExporterName { get; set; }
        public long ExporterCountry { get; set; }
        public string ImportersRegister { get; set; }
        public string CountryNameAR { get; set; }
        public string LoginName { get; set; }
        public string Password { get; set; }
        public string UserType { get; set; }
        public string DataEntererName { get; set; }
    }
}
