//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileAppServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vIssue
    {
        public string IssueType { get; set; }
        public long Id { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<long> FormNo { get; set; }
        public string LoginName { get; set; }
        public string IssueDesc { get; set; }
        public int Status { get; set; }
        public byte[] Attach { get; set; }
        public string ResolvedBy { get; set; }
        public string IssueStatus { get; set; }
        public string IssueDate { get; set; }
        public string ResolveComment { get; set; }
        public System.DateTime Expr1 { get; set; }
        public Nullable<long> Bank { get; set; }
        public Nullable<long> BankBranch { get; set; }
        public Nullable<long> BankEX { get; set; }
        public Nullable<long> BranchEX { get; set; }
        public string ObjectName { get; set; }
        public int IsTraderEditable { get; set; }
        public string FullName { get; set; }
    }
}
