//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileAppServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vMaturityStatus
    {
        public long MaturityID { get; set; }
        public long MaturityCode { get; set; }
        public long FormCode { get; set; }
        public System.DateTime MaturityDate { get; set; }
        public string MaturityDateString { get; set; }
        public decimal Amount { get; set; }
        public long Currency { get; set; }
        public long FlowStatus { get; set; }
        public long DataEnterer { get; set; }
        public System.DateTime ActionTime { get; set; }
        public decimal AmountUSD { get; set; }
        public decimal Rate { get; set; }
        public long Bank { get; set; }
        public long Branch { get; set; }
        public string CurrnecyNameAR { get; set; }
        public string BankNameAR { get; set; }
        public string BranchNameAR { get; set; }
        public string FlowStatusNameIM { get; set; }
        public Nullable<decimal> MaturityRemaining { get; set; }
        public long BankBranch { get; set; }
        public string LoginName { get; set; }
        public string MaturityStatus { get; set; }
        public string Password { get; set; }
        public string FullName { get; set; }
    }
}
