//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileAppServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vMaturitySettlement
    {
        public long MaturitySettlementCode { get; set; }
        public long MaturitySettlementID { get; set; }
        public long MaturityCode { get; set; }
        public decimal Amount { get; set; }
        public long Currency { get; set; }
        public decimal Rate { get; set; }
        public decimal AmountUSD { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public string PaymentDateString { get; set; }
        public System.DateTime ActionTime { get; set; }
        public long FlowStatus { get; set; }
        public long Status { get; set; }
        public long DateEnterer { get; set; }
        public long IsDeleted { get; set; }
        public string RejectionNotes { get; set; }
        public long SecondApproval { get; set; }
        public long FirstApproval { get; set; }
        public long MaturitySettlementType { get; set; }
        public long Bank { get; set; }
        public long Branch { get; set; }
        public string MaturitySettlementTypeDesc { get; set; }
        public string FlowStatusNameIM { get; set; }
        public string CurrencyShortName { get; set; }
        public long FormCode { get; set; }
        public string Password { get; set; }
        public string LoginName { get; set; }
        public long BankBranch { get; set; }
        public long Expr1 { get; set; }
        public long Expr2 { get; set; }
        public string FullName { get; set; }
    }
}
