//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileAppServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vOperationTransfer
    {
        public Nullable<decimal> TransferAmount { get; set; }
        public Nullable<long> TransferCode { get; set; }
        public Nullable<System.DateTime> TransferDate { get; set; }
        public string CorrespondentName { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<long> Currency { get; set; }
        public Nullable<long> Branch { get; set; }
        public Nullable<long> Bank { get; set; }
        public string TrsDateString { get; set; }
        public string ClientName { get; set; }
        public Nullable<decimal> TransferRemaining { get; set; }
        public string CurrencyShortName { get; set; }
        public decimal Deduction { get; set; }
        public decimal DeductionUSD { get; set; }
        public Nullable<long> OperationCode { get; set; }
        public Nullable<long> CBOSID { get; set; }
        public string BankNameAR { get; set; }
        public string BranchNameAR { get; set; }
        public Nullable<long> TrsID { get; set; }
        public string FullName { get; set; }
        public string LoginName { get; set; }
        public string Password { get; set; }
    }
}
