//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileAppServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vOperationCommodity
    {
        public long InitInvoiceID { get; set; }
        public System.DateTime CreationDate { get; set; }
        public long OpCode { get; set; }
        public System.DateTime InitInvoiceDate { get; set; }
        public string InitInvoiceNumber { get; set; }
        public string InitInvoiceIssuer { get; set; }
        public long Currency { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public decimal TotalValue { get; set; }
        public Nullable<decimal> TotalValueUSD { get; set; }
        public string CommodityDesc { get; set; }
        public long DataEnterrer { get; set; }
        public string CurrencyShortName { get; set; }
        public string InitInvoiceDateString { get; set; }
        public long OperationCode { get; set; }
        public long Bank { get; set; }
        public long Branch { get; set; }
        public string FullName { get; set; }
        public string LoginName { get; set; }
        public string Password { get; set; }
    }
}
