//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileAppServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vPayment
    {
        public long PaymentId { get; set; }
        public long PaymentCode { get; set; }
        public System.DateTime CreationTime { get; set; }
        public long PaymentType { get; set; }
        public long PaymentMethodType { get; set; }
        public long CBOSID { get; set; }
        public decimal AmountUSD { get; set; }
        public long Currency { get; set; }
        public decimal Amount { get; set; }
        public decimal Discounts { get; set; }
        public decimal Rate { get; set; }
        public string CorrespondentName { get; set; }
        public string CorrespondentAccount { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public long Bank { get; set; }
        public long BankBranch { get; set; }
        public string RejectionNotes { get; set; }
        public string Note { get; set; }
        public long PaymentStatus { get; set; }
        public long FlowStatus { get; set; }
        public long FirstApproval { get; set; }
        public long DataEntereer { get; set; }
        public long SecondApproval { get; set; }
        public System.Guid UGUID { get; set; }
        public Nullable<decimal> PaymentRemaining { get; set; }
        public string LoginName { get; set; }
        public string Password { get; set; }
        public string CurrencyShortName { get; set; }
        public string BankNameAR { get; set; }
        public string BranchNameAR { get; set; }
        public string FlowStatusNamePayment { get; set; }
        public string FullName { get; set; }
    }
}
