//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileAppServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vSupportedDouments
    {
        public Nullable<long> Code { get; set; }
        public string RelatedObject { get; set; }
        public string DocumentName { get; set; }
        public Nullable<long> FileSize { get; set; }
        public string ContentType { get; set; }
        public byte[] DocumentData { get; set; }
        public string DocumentDesc { get; set; }
        public string LoginName { get; set; }
        public System.DateTime ActionTime { get; set; }
        public string Password { get; set; }
        public long Id { get; set; }
        public string ObjectName { get; set; }
        public string FullName { get; set; }
    }
}
